#!/usr/bin/python3
from argparse import ArgumentParser

from src.puzzle import Mode, Puzzle

if __name__ == "__main__":
    # Command-line arguments parser
    parser = ArgumentParser(
        prog="BMPuzzle", 
        description="BMP puzzle generator and solver tool.",
        epilog="Example: ./bmpuzzle generator --input input.bmp --output puzzle.bmp --secret 1234567890 --block-size 100x100")

    # Common args (parent parser)
    common = ArgumentParser(add_help=False)
    common.add_argument("-i", "--input",
                        help="source Image filename",
                        type=str, required=True)
    common.add_argument("-o", "--output",
                        help="output Image filename",
                        type=str, required=True)
    common.add_argument("-s", "--secret",
                        help="secret value",
                        required=True)
    common.add_argument("-b", "--block-size",
                        help="block size in pixels, format 'widthxheight' (must evenly divide the image size)",
                        type=str, required=True)
    common.add_argument("-d", "--debug",
                        help="debug",
                        action="store_true")

    # Subparsers
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("generator", parents=[common], help="Generate a puzzle")
    subparsers.add_parser("solver", parents=[common], help="Solve a puzzle")

    args = parser.parse_args()

    # Retrive Data
    src = args.input
    out = args.output
    secret = args.secret

    if args.block_size is not None:
        b_width, b_height = args.block_size.split("x")
        b_width, b_height = int(b_width), int(b_height)
    else:
        b_width, b_height = -1, -1

    """
    print(src)
    print(out)
    print(secret)
    print(f'{b_height}x{b_width}')
    """

    # Launch
    status_code = 1
    bmpuzzle = Puzzle(src, b_width, b_height, args.debug)
    if args.command == "generator":
        status_code = bmpuzzle.run(Mode.GENERATOR, out, secret)
    elif args.command == "solver":
        status_code = bmpuzzle.run(Mode.SOLVER, out, secret)

    exit(status_code)
